#!/usr/bin/env sh
# load the scripting additions
sudo yabai --load-sa

# colours
source ~/.cache/wal/colors.sh
CB=$(echo $background | sed 's/#//')
CF=$(echo $foreground | sed 's/#//')
C1=$(echo $color1 | sed 's/#//')
C2=$(echo $color2 | sed 's/#//')
C3=$(echo $color3 | sed 's/#//')
C4=$(echo $color4 | sed 's/#//')
C5=$(echo $color5 | sed 's/#//')
C6=$(echo $color6 | sed 's/#//')

# border
yabai -m config window_border                on
yabai -m config window_border_width          8
yabai -m config active_window_border_color   0xff$C1
yabai -m config normal_window_border_color   0xff$CB
yabai -m config insert_window_border_color   0xff$CF

# gaps
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   12

# window appearance
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                float
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90

# window placement
yabai -m config auto_balance                 on
yabai -m config window_placement             second_child
yabai -m config window_topmost               off

# mouse 
yabai -m config mouse_modifier               cmd
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off

# create workspsaces
$HOME/scripts/yabaictl create_workspaces

# rules


yabai -m rule --add app="^System Preferences$" manage=off

echo "yabai configuration loaded.."
