#!/usr/bin/env node
const system = require('child_process')

/**
* Function to issue bash commands, returns the stdout.
* @param command
* @returns {string} stdout
*/
function shell (command, ...args) {
  const shell_args = args.length ? args : []
  let shell_out = ''
  try {
    shell_out = system.spawnSync(command, shell_args)
  } catch(error) {
    shell_out = error
  }

  return {
    status: shell_out.status,
    stdout: shell_out.stdout.toString(),
    stderr: shell_out.stderr.toString()
  }
}

function space_next (direction) {
  const spaces = JSON.parse(yabai_message('query', 'spaces', '--display').stdout)
  const { index } = JSON.parse(yabai_message('query', 'spaces', '--space').stdout)

  const index_next = direction === 'north'
    ? index + 1
    : index - 1
  
  const index_first = spaces[0].index
  const index_last = spaces[spaces.length - 1].index

  if (index_next > index_last) {
    return index_first
  } else if (index_next < index_first) {
    return index_last
  } else {
    return index_next
  }
}

function display_next (direction) {
  const displays = JSON.parse(yabai_message('query', 'displays', '').stdout)
  const { index } = JSON.parse(yabai_message('query', 'displays', '--display').stdout)

  const index_next = direction === 'east'
    ? index + 1
    : index - 1
  
  const index_first = displays[0].index
  const index_last = displays[displays.length - 1].index

  if (index_next > index_last) {
    return index_first
  } else if (index_next < index_first) {
    return index_last
  } else {
    return index_next
  }
}

function workspace_is_empty () {
  return JSON.parse(yabai_message('query', 'windows', '--space').stdout)
    .filter(({ floating, visible, minimized }) => 
      floating !== 1 && 
      visible !== 0 &&
      minimized !== 1
    ).length === 0
}

function position_adjacent (direction) {
  switch(direction) {
    case "east":
      return "first"
    case "west":
      return "last"
    case "south":
      return "first"
    case "north":
      return "last"
  }
}

function yabai_message(type, action, subaction) {
  return shell('yabai', '-m', type, `--${action}`, subaction)
}

function yabai_focus(direction) {
  const focus_adjacent_window = yabai_message('window', 'focus', direction)

  if (focus_adjacent_window.status !== 0) {
    if (direction === 'east' || direction === 'west') {
      const index = display_next(direction)

      yabai_message('display', 'focus', index)
    } else if (direction === 'north' || direction === 'south') {
      const index = space_next(direction)

      yabai_message('space', 'focus', index)
    }

    if (!workspace_is_empty()) {
      const position = position_adjacent(direction)
      yabai_message('window', 'focus', position)
    }
  }
}

function yabai_move(direction) {
  const warp_adjacent_window = yabai_message('window', 'swap', direction)

  if (warp_adjacent_window.status !== 0) {
    if (direction === 'east' || direction === 'west') {
      const index = display_next(direction)
      
      yabai_message('window', 'display', index)
      yabai_message('display', 'focus', index)
      
    } else if (direction === 'north' || direction === 'south') {
      const index = space_next(direction)
      
      yabai_message('window', 'space', index)
      yabai_message('space', 'focus', index)
    }

    const position = position_adjacent(direction)
    yabai_message('window', 'focus', position)
  }
}

function yabai_resize(direction) {
  const amount = 100

  if (direction === 'west') {
    const resize_west = yabai_message('window', 'resize', `left:-${amount}:0`)

    if (resize_west.status !== 0) {
      yabai_message('window', 'resize', `right:-${amount}:0`)
    }
  } else if (direction === 'east') {
    const resize_east = yabai_message('window', 'resize', `left:${amount}:0`)

    if (resize_east.status !== 0) {
      yabai_message('window', 'resize', `right:${amount}:0`)
    }
  } else if (direction === 'north') {
    const resize_north = yabai_message('window', 'resize', `bottom:0:-${amount}`)

    if (resize_north.status !== 0) {
      yabai_message('window', 'resize', `top:0:-${amount}`)
    }
  } else if (direction === 'south') {
    const resize_south = yabai_message('window', 'resize', `bottom:0:${amount}`)

    if (resize_south.status !== 0) {
      yabai_message('window', 'resize', `top:0:${amount}`)
    }
  }
}

async function main () {
  const args = process.argv
  const action = args[2]
  const direction = args[3]

  switch (action) {
    case 'focus':
      yabai_focus(direction)  
      break
    case 'move':
      yabai_move(direction)
      break
    case 'resize':
      yabai_resize(direction)
      break
  }
}

try {
  main()
} catch (error) {
  console.error(error)
}
