#!/usr/bin/env node
const system = require('child_process')

/**
* Function to issue bash commands, returns the stdout.
* @param command
* @returns {string} stdout
*/
function shell (command, ...args) {
  const shell_args = args.length ? args : []
  let shell_out = ''
  try {
    shell_out = system.spawnSync(command, shell_args)
  } catch(error) {
    shell_out = error
  }

  return {
    status: shell_out.status,
    stdout: shell_out.stdout.toString(),
    stderr: shell_out.stderr.toString()
  }
}

function direction_alt (direction) {
  switch(direction) {
    case "east":
      return "right"
    case "west":
      return "left"
    case "south":
      return "down"
    case "north":
      return "up"
  }
}

function direction_reverse (direction) {
  switch(direction) {
    case "east":
      return "west"
    case "west":
      return "east"
    case "south":
      return "north"
    case "north":
      return "south"
  }
}

function workspace_type (direction) {
  switch(direction) {
    case "east":
      return "display"
    case "west":
      return "display"
    case "south":
      return "space"
    case "north":
      return "space"
  }
}

function workspace_next (direction) {
  switch(direction) {
    case "east":
      return "next"
    case "west":
      return "prev"
    case "south":
      return "next"
    case "north":
      return "prev"
  }
}

function workspace_reverse(direction) {
  switch(direction) {
    case "east":
      return "prev"
      case "west":
      return "next"
    case "south":
      return "prev"
      case "north":
      return "next"
  }
}

function position_adjacent (direction) {
  switch(direction) {
    case "east":
      return "first"
    case "west":
      return "last"
    case "south":
      return "first"
    case "north":
      return "last"
  }
}

function yabai_message(type, action, direction) {
  return shell('yabai', '-m', type, `--${action}`, direction)
}

function yabai_focus(direction) {
  const focus_adjacent_window = yabai_message('window', 'focus', direction)

  if (focus_adjacent_window.status !== 0) {
    const wrk_nxt = workspace_next(direction)
    const wrk_typ = workspace_type(direction)
    const pos_adj = position_adjacent(direction)

    const focus_next_workspace = yabai_message(wrk_typ, 'focus', wrk_nxt)
      
    if (focus_next_workspace.status !== 0) {
      const wrk_rev = workspace_reverse(direction)

      yabai_message(wrk_typ, 'focus', wrk_rev)
    }
    
    yabai_message('window', 'focus', pos_adj)
  }
}

function yabai_warp(direction) {
  const warp_adjacent_window = yabai_message('window', 'warp', direction)

  if (warp_adjacent_window.status !== 0) {
    const wrk_nxt = workspace_next(direction)
    const wrk_typ = workspace_type(direction)
    const pos_adj = position_adjacent(direction)

    const warp_next_workspace = yabai_message('window', wrk_typ, wrk_nxt)
    
    if (warp_next_workspace.status !== 0) {
      const wrk_rev = workspace_reverse(direction)

      yabai_message('window', wrk_typ, wrk_rev)
      yabai_message(wrk_typ, 'focus', wrk_rev)
    } else {
      yabai_message(wrk_typ, 'focus', wrk_nxt)
    }

    yabai_message('window', 'warp', pos_adj)
  }
}

function yabai_resize(direction) {
  const amount = 100

  if (direction === 'west') {
    const resize_west = yabai_message('window', 'resize', `left:-${amount}:0`)

    if (resize_west.status !== 0) {
      yabai_message('window', 'resize', `right:-${amount}:0`)
    }
  } else if (direction === 'east') {
    const resize_east = yabai_message('window', 'resize', `left:${amount}:0`)

    if (resize_east.status !== 0) {
      yabai_message('window', 'resize', `right:${amount}:0`)
    }
  } else if (direction === 'north') {
    const resize_north = yabai_message('window', 'resize', `bottom:0:-${amount}`)

    if (resize_north.status !== 0) {
      yabai_message('window', 'resize', `top:0:-${amount}`)
    }
  } else if (direction === 'south') {
    const resize_south = yabai_message('window', 'resize', `bottom:0:${amount}`)

    if (resize_south.status !== 0) {
      yabai_message('window', 'resize', `top:0:${amount}`)
    }
  }
}

async function main () {
  const args = process.argv
  const action = args[2]
  const direction = args[3]

  switch (action) {
    case 'focus':
      yabai_focus(direction)  
      break
    case 'warp':
      yabai_warp(direction)
      break
    case 'resize':
      yabai_resize(direction)
      break
  }
}

try {
  main()
} catch (error) {
  console.error(error)
}
